insert into app_users (username)
values ('trend-tester')
on conflict (username) do nothing;

with trend_user as (
  select id
  from app_users
  where username = 'trend-tester'
),
seed_sessions (
  id,
  requested_subjects,
  preset_key,
  question_target,
  batch_size,
  timer_enabled,
  timer_duration_minutes,
  status,
  current_batch_index,
  total_correct,
  total_answered,
  analysis_state,
  warnings,
  started_at,
  completed_at
) as (
  values
    (
      '7a1b62c0-1111-4a5d-8f01-100000000001'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      12,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":4,"total":7},"Chemistry":{"correct":3,"total":7},"General Maths":{"correct":5,"total":6}},"batchHistory":[{"batchIndex":0,"correct":2,"total":5,"accuracy":40},{"batchIndex":1,"correct":3,"total":5,"accuracy":60},{"batchIndex":2,"correct":2,"total":5,"accuracy":40},{"batchIndex":3,"correct":2,"total":5,"accuracy":40}]}'::jsonb,
      '[]'::jsonb,
      date_trunc('hour', now()) - interval '22 hours',
      date_trunc('hour', now()) - interval '21 hours 10 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000002'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      14,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":4,"total":6},"Chemistry":{"correct":4,"total":7},"General Maths":{"correct":6,"total":7}},"batchHistory":[{"batchIndex":0,"correct":3,"total":5,"accuracy":60},{"batchIndex":1,"correct":4,"total":5,"accuracy":80},{"batchIndex":2,"correct":3,"total":5,"accuracy":60},{"batchIndex":3,"correct":4,"total":5,"accuracy":80}]}'::jsonb,
      '[]'::jsonb,
      date_trunc('hour', now()) - interval '18 hours',
      date_trunc('hour', now()) - interval '16 hours 55 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000003'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      15,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":5,"total":7},"Chemistry":{"correct":4,"total":6},"General Maths":{"correct":6,"total":7}},"batchHistory":[{"batchIndex":0,"correct":4,"total":5,"accuracy":80},{"batchIndex":1,"correct":4,"total":5,"accuracy":80},{"batchIndex":2,"correct":3,"total":5,"accuracy":60},{"batchIndex":3,"correct":4,"total":5,"accuracy":80}]}'::jsonb,
      '[]'::jsonb,
      date_trunc('hour', now()) - interval '14 hours',
      date_trunc('hour', now()) - interval '12 hours 45 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000004'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      16,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":5,"total":6},"Chemistry":{"correct":5,"total":7},"General Maths":{"correct":6,"total":7}},"batchHistory":[{"batchIndex":0,"correct":4,"total":5,"accuracy":80},{"batchIndex":1,"correct":4,"total":5,"accuracy":80},{"batchIndex":2,"correct":4,"total":5,"accuracy":80},{"batchIndex":3,"correct":4,"total":5,"accuracy":80}]}'::jsonb,
      '[]'::jsonb,
      date_trunc('hour', now()) - interval '10 hours',
      date_trunc('hour', now()) - interval '8 hours 35 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000005'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      17,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":6,"total":7},"Chemistry":{"correct":5,"total":6},"General Maths":{"correct":6,"total":7}},"batchHistory":[{"batchIndex":0,"correct":4,"total":5,"accuracy":80},{"batchIndex":1,"correct":4,"total":5,"accuracy":80},{"batchIndex":2,"correct":4,"total":5,"accuracy":80},{"batchIndex":3,"correct":5,"total":5,"accuracy":100}]}'::jsonb,
      '[]'::jsonb,
      date_trunc('hour', now()) - interval '6 hours',
      date_trunc('hour', now()) - interval '4 hours 50 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000006'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      18,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":6,"total":6},"Chemistry":{"correct":5,"total":7},"General Maths":{"correct":7,"total":7}},"batchHistory":[{"batchIndex":0,"correct":4,"total":5,"accuracy":80},{"batchIndex":1,"correct":5,"total":5,"accuracy":100},{"batchIndex":2,"correct":4,"total":5,"accuracy":80},{"batchIndex":3,"correct":5,"total":5,"accuracy":100}]}'::jsonb,
      '[]'::jsonb,
      date_trunc('hour', now()) - interval '2 hours',
      date_trunc('hour', now()) - interval '1 hour 5 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000007'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      10,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":3,"total":7},"Chemistry":{"correct":3,"total":6},"General Maths":{"correct":4,"total":7}}}'::jsonb,
      '[]'::jsonb,
      date_trunc('day', now()) - interval '1 day' + interval '9 hours',
      date_trunc('day', now()) - interval '1 day' + interval '10 hours 10 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000008'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      11,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":4,"total":7},"Chemistry":{"correct":3,"total":7},"General Maths":{"correct":4,"total":6}}}'::jsonb,
      '[]'::jsonb,
      date_trunc('day', now()) - interval '2 day' + interval '10 hours',
      date_trunc('day', now()) - interval '2 day' + interval '11 hours 5 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000009'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      13,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":4,"total":6},"Chemistry":{"correct":4,"total":7},"General Maths":{"correct":5,"total":7}}}'::jsonb,
      '[]'::jsonb,
      date_trunc('day', now()) - interval '3 day' + interval '11 hours',
      date_trunc('day', now()) - interval '3 day' + interval '12 hours 15 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000010'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      12,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":4,"total":7},"Chemistry":{"correct":4,"total":7},"General Maths":{"correct":4,"total":6}}}'::jsonb,
      '[]'::jsonb,
      date_trunc('day', now()) - interval '4 day' + interval '9 hours',
      date_trunc('day', now()) - interval '4 day' + interval '10 hours 25 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000011'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      15,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":5,"total":7},"Chemistry":{"correct":5,"total":6},"General Maths":{"correct":5,"total":7}}}'::jsonb,
      '[]'::jsonb,
      date_trunc('day', now()) - interval '5 day' + interval '8 hours',
      date_trunc('day', now()) - interval '5 day' + interval '9 hours 40 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000012'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      16,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":6,"total":7},"Chemistry":{"correct":4,"total":6},"General Maths":{"correct":6,"total":7}}}'::jsonb,
      '[]'::jsonb,
      date_trunc('day', now()) - interval '6 day' + interval '10 hours',
      date_trunc('day', now()) - interval '6 day' + interval '11 hours 15 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000013'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      9,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":3,"total":7},"Chemistry":{"correct":2,"total":6},"General Maths":{"correct":4,"total":7}}}'::jsonb,
      '[]'::jsonb,
      date_trunc('week', now()) + interval '2 day 10 hours' - interval '28 days',
      date_trunc('week', now()) + interval '2 day 11 hours 20 minutes' - interval '28 days'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000014'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      11,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":3,"total":6},"Chemistry":{"correct":4,"total":7},"General Maths":{"correct":4,"total":7}}}'::jsonb,
      '[]'::jsonb,
      date_trunc('week', now()) + interval '2 day 10 hours' - interval '21 days',
      date_trunc('week', now()) + interval '2 day 11 hours 25 minutes' - interval '21 days'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000015'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      13,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":4,"total":6},"Chemistry":{"correct":4,"total":7},"General Maths":{"correct":5,"total":7}}}'::jsonb,
      '[]'::jsonb,
      date_trunc('week', now()) + interval '2 day 10 hours' - interval '14 days',
      date_trunc('week', now()) + interval '2 day 11 hours 30 minutes' - interval '14 days'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000016'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      15,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":5,"total":6},"Chemistry":{"correct":5,"total":7},"General Maths":{"correct":5,"total":7}}}'::jsonb,
      '[]'::jsonb,
      date_trunc('week', now()) + interval '2 day 10 hours' - interval '7 days',
      date_trunc('week', now()) + interval '2 day 11 hours 15 minutes' - interval '7 days'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000017'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      8,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":2,"total":7},"Chemistry":{"correct":3,"total":7},"General Maths":{"correct":3,"total":6}}}'::jsonb,
      '[]'::jsonb,
      date_trunc('month', now()) - interval '11 months' + interval '8 day 10 hours',
      date_trunc('month', now()) - interval '11 months' + interval '8 day 11 hours 20 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000018'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      10,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":3,"total":7},"Chemistry":{"correct":3,"total":6},"General Maths":{"correct":4,"total":7}}}'::jsonb,
      '[]'::jsonb,
      date_trunc('month', now()) - interval '9 months' + interval '7 day 10 hours',
      date_trunc('month', now()) - interval '9 months' + interval '7 day 11 hours 25 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000019'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      11,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":4,"total":7},"Chemistry":{"correct":3,"total":7},"General Maths":{"correct":4,"total":6}}}'::jsonb,
      '[]'::jsonb,
      date_trunc('month', now()) - interval '7 months' + interval '9 day 10 hours',
      date_trunc('month', now()) - interval '7 months' + interval '9 day 11 hours 40 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000020'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      13,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":4,"total":6},"Chemistry":{"correct":4,"total":7},"General Maths":{"correct":5,"total":7}}}'::jsonb,
      '[]'::jsonb,
      date_trunc('month', now()) - interval '5 months' + interval '6 day 10 hours',
      date_trunc('month', now()) - interval '5 months' + interval '6 day 11 hours 30 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000021'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      15,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":5,"total":7},"Chemistry":{"correct":5,"total":6},"General Maths":{"correct":5,"total":7}}}'::jsonb,
      '[]'::jsonb,
      date_trunc('month', now()) - interval '3 months' + interval '5 day 10 hours',
      date_trunc('month', now()) - interval '3 months' + interval '5 day 11 hours 50 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000022'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      16,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":5,"total":6},"Chemistry":{"correct":5,"total":7},"General Maths":{"correct":6,"total":7}}}'::jsonb,
      '[]'::jsonb,
      date_trunc('month', now()) - interval '1 months' + interval '4 day 10 hours',
      date_trunc('month', now()) - interval '1 months' + interval '4 day 11 hours 10 minutes'
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000023'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      6,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":2,"total":7},"Chemistry":{"correct":2,"total":6},"General Maths":{"correct":2,"total":7}}}'::jsonb,
      '[]'::jsonb,
      make_timestamptz(extract(year from now())::int - 3, 4, 18, 10, 0, 0),
      make_timestamptz(extract(year from now())::int - 3, 4, 18, 11, 15, 0)
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000024'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      9,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":3,"total":7},"Chemistry":{"correct":2,"total":7},"General Maths":{"correct":4,"total":6}}}'::jsonb,
      '[]'::jsonb,
      make_timestamptz(extract(year from now())::int - 2, 5, 16, 10, 0, 0),
      make_timestamptz(extract(year from now())::int - 2, 5, 16, 11, 20, 0)
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000025'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      12,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":4,"total":7},"Chemistry":{"correct":4,"total":6},"General Maths":{"correct":4,"total":7}}}'::jsonb,
      '[]'::jsonb,
      make_timestamptz(extract(year from now())::int - 1, 6, 14, 10, 0, 0),
      make_timestamptz(extract(year from now())::int - 1, 6, 14, 11, 10, 0)
    ),
    (
      '7a1b62c0-1111-4a5d-8f01-100000000026'::uuid,
      '["Physics","Chemistry","General Maths"]'::jsonb,
      'jee',
      30,
      5,
      true,
      180,
      'completed',
      6,
      14,
      20,
      '{"subjectBreakdown":{"Physics":{"correct":5,"total":7},"Chemistry":{"correct":4,"total":7},"General Maths":{"correct":5,"total":6}}}'::jsonb,
      '[]'::jsonb,
      make_timestamptz(extract(year from now())::int, 1, 12, 10, 0, 0),
      make_timestamptz(extract(year from now())::int, 1, 12, 11, 5, 0)
    )
)
insert into quiz_sessions (
  id,
  user_id,
  username_snapshot,
  requested_subjects,
  preset_key,
  question_target,
  batch_size,
  timer_enabled,
  timer_duration_minutes,
  timer_ends_at,
  status,
  current_batch_index,
  total_correct,
  total_answered,
  analysis_state,
  warnings,
  started_at,
  completed_at
)
select
  seed.id,
  trend_user.id,
  'trend-tester',
  seed.requested_subjects,
  seed.preset_key,
  seed.question_target,
  seed.batch_size,
  seed.timer_enabled,
  seed.timer_duration_minutes,
  seed.completed_at + interval '3 hours',
  seed.status,
  seed.current_batch_index,
  seed.total_correct,
  seed.total_answered,
  seed.analysis_state,
  seed.warnings,
  seed.started_at,
  seed.completed_at
from seed_sessions seed
cross join trend_user
on conflict (id) do update set
  requested_subjects = excluded.requested_subjects,
  preset_key = excluded.preset_key,
  question_target = excluded.question_target,
  batch_size = excluded.batch_size,
  timer_enabled = excluded.timer_enabled,
  timer_duration_minutes = excluded.timer_duration_minutes,
  timer_ends_at = excluded.timer_ends_at,
  status = excluded.status,
  current_batch_index = excluded.current_batch_index,
  total_correct = excluded.total_correct,
  total_answered = excluded.total_answered,
  analysis_state = excluded.analysis_state,
  warnings = excluded.warnings,
  started_at = excluded.started_at,
  completed_at = excluded.completed_at;
